##key-store: 表示密钥文件名
##key-alias: 表示密钥别名
##key-store-password: cmd命令执行过程中输入的密码

server:
  ssl:
    key-store: server.keystore
    key-alias: tomcathttps
    enabled: true
    key-store-password: 123456
  port: 443