server:
  #设置Web容器端口号
  port: 8080

###自定义配置属性值
#配置文件赋值
com:
  people:
    #String
    name: SpringBoot通过yaml方式取值
    petName: 旺财
    age: 10
    #map
    user: {username: admin,password: 123456}
    #list
    type: [properties,yaml]
    #Object
    pet:
      breed: dog
      #配置文件取值
      name: ${com.louis.petName}

##thymeleaf静态资源配置
spring:
  thymeleaf:
    #模版模式
    mode: HTML5
    #编码
    encoding: UTF-8
    servlet:
      content-type: text/html
    #关闭模版缓存，即时刷新
    cache: false
    prefix: classpath:/templates/
    suffix: .html