server:
  #设置Web容器端口号
  port: 9090
  servlet:
    #表示项目名称。不配置时默认为/
    context-path: /yml
  tomcat:
    #表示配置tomcat请求编码
    uri-encoding: UTF-8

###自定义配置属性值
#配置文件赋值
com:
  people:
    #String
    name: SpringBoot通过yaml方式取值
    petName: 旺财
    #map
    user: {username: admin,password: 123456}
    #list
    type: [properties,yaml]
    #Object
    pet:
      breed: dog
      #配置文件取值
      name: ${com.people.petName}