spring:
  #JDBC配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?characterEncoding=utf-8&autoReconnect=true&useSSL=false&useUnicode=true&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
  #JPA配置
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    #读取实体类column注解数据
    hibernate:
      ddl-auto: update
      #JPA映射策略：不做修改，直接映射
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8