spring:
  datasource:
    name: mytest
    #基本属性 url user password
    url: jdbc:mysql://localhost:3306/master?characterEncoding=utf-8&autoReconnect=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 采用数据库存储方式
  quartz:
    job-store-type: jdbc

mybatis:
  #mapper映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #检查配置文件是否存在
  check-config-location: true
  #定义别名所在包
  type-aliases-package: com.springboot.entity

#showSQL
logging:
  level:
    com.springboot.dao: debug