spring:
  data:    mongodb:      host: 127.0.0.1
      port: 27017
      database: test
  jackson:    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:  level:    org.springframework.data.mongodb.core.MongoTemplate: DEBUG #配置MongoTemplate日志